/**
 * Auto-generated ring-fenced practice samples for /learn pages.
 * Regenerated by scripts/build-learn-sample-pool.mjs — do not hand-edit.
 * Excludes mock_suitable, mock.json prompts, and FREE_MOCK_QUESTIONS.
 */

export type LearnSampleMcq = {
  id: string;
  lo_number: number;
  lo_code: string;
  lo_title: string;
  type: "mcq" | "scenario_mcq";
  prompt: string;
  options: string[];
  correct_answer: string;
  marks: number;
  explanation: string | null;
};

export type LearnSampleDropdown = {
  id: string;
  lo_number: number;
  lo_code: string;
  lo_title: string;
  type: "dropdown";
  prompt: string;
  dropdowns: Record<string, string[]>;
  correct_answers: Record<string, string>;
  marks: number;
  explanation: string | null;
};

export type LearnSampleQuestion = LearnSampleMcq | LearnSampleDropdown;

export const LEARN_SAMPLE_POOL: LearnSampleQuestion[] = [
  {
    "id": "LO1-q8",
    "lo_number": 1,
    "lo_code": "LO1",
    "lo_title": "Life cycles",
    "type": "mcq",
    "prompt": "A project manager says: 'Hybrid life cycles mean there are no fixed rules, so the team can do whatever works.' What is wrong with this statement?",
    "marks": 1,
    "explanation": "Hybrid is a deliberate, structured combination of linear and iterative approaches — not an absence of rules.",
    "options": [
      "Hybrid combines linear and iterative deliberately, and requires more skill, not less, to manage multiple ways of working in parallel.",
      "Hybrid life cycles are only used in IT projects.",
      "Hybrid life cycles are identical to linear life cycles.",
      "Hybrid life cycles cannot include any linear phases."
    ],
    "correct_answer": "A"
  },
  {
    "id": "LO1-q18",
    "lo_number": 1,
    "lo_code": "LO1",
    "lo_title": "Life cycles",
    "type": "mcq",
    "prompt": "A colleague says: 'The life cycle choice is the project manager's decision alone.' What's the correct position?",
    "marks": 1,
    "explanation": "Life cycle choice involves the sponsor and governance board, shaped by context, culture, project needs and appetite for change — not the PM's decision in isolation.",
    "options": [
      "Choice is shaped by organisational context, culture, project needs and stakeholder appetite — the sponsor and governance board are involved",
      "The client always mandates the life cycle in the contract, so the PM has no input",
      "Life cycle choice is fixed by the APM Body of Knowledge and cannot vary by project",
      "Only the delivery team, not the PM, decides which life cycle to use"
    ],
    "correct_answer": "A"
  },
  {
    "id": "LO3-q5",
    "lo_number": 3,
    "lo_code": "LO3",
    "lo_title": "Sustainability",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — Balancing environmental, social, economic and administrative factors across the project's whole life cycle, as both an individual and organisational responsibility.. __(b)__ — Effect on climate, biodiversity, energy use..",
    "marks": 2,
    "explanation": "Sustainability matches \"Balancing environmental, social, economic and administrative factors across the project's whole life cycle, as both an individual and organisational responsibility.\", and Environmental impact matches \"Effect on climate, biodiversity, energy use.\".",
    "dropdowns": {
      "a": [
        "Sustainability",
        "Environmental impact",
        "Social impact",
        "Economic impact"
      ],
      "b": [
        "Environmental impact",
        "Sustainability",
        "Social impact",
        "Economic impact"
      ]
    },
    "correct_answers": {
      "a": "Sustainability",
      "b": "Environmental impact"
    }
  },
  {
    "id": "LO3-q9",
    "lo_number": 3,
    "lo_code": "LO3",
    "lo_title": "Sustainability",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — Effect on people: human rights, equity, equality, community.. __(b)__ — Affordability, profit, risk management..",
    "marks": 2,
    "explanation": "Social impact matches \"Effect on people: human rights, equity, equality, community.\", and Economic impact matches \"Affordability, profit, risk management.\".",
    "dropdowns": {
      "a": [
        "Social impact",
        "Sustainability",
        "Environmental impact",
        "Economic impact"
      ],
      "b": [
        "Economic impact",
        "Sustainability",
        "Environmental impact",
        "Social impact"
      ]
    },
    "correct_answers": {
      "a": "Social impact",
      "b": "Economic impact"
    }
  },
  {
    "id": "LO3-q15",
    "lo_number": 3,
    "lo_code": "LO3",
    "lo_title": "Sustainability",
    "type": "dropdown",
    "prompt": "Sustainability considerations apply across a project output's whole life cycle, including creation, use, and __(a)__. Ignoring social equity risks failing to meet the needs of __(b)__ groups.",
    "marks": 2,
    "explanation": "Sustainability spans the whole life cycle including disposal/decommissioning, and ignoring social equity risks failing vulnerable groups' needs.",
    "dropdowns": {
      "a": [
        "disposal and decommissioning",
        "the business case only",
        "the concept phase only",
        "procurement only"
      ],
      "b": [
        "vulnerable",
        "senior",
        "shareholder",
        "supplier"
      ]
    },
    "correct_answers": {
      "a": "disposal and decommissioning",
      "b": "vulnerable"
    }
  },
  {
    "id": "LO3-q18",
    "lo_number": 3,
    "lo_code": "LO3",
    "lo_title": "Sustainability",
    "type": "mcq",
    "prompt": "A colleague says: 'Sustainability KPIs are nice-to-have add-ons.' What's the correct position?",
    "marks": 1,
    "explanation": "KPIs and related measures are core, not optional, mechanisms for monitoring and reporting sustainability.",
    "options": [
      "KPIs, ESG data, and operational and embodied carbon measures are core mechanisms by which sustainability is monitored and reported",
      "KPIs are only relevant for financial reporting",
      "KPIs are optional unless a regulator specifically requests them",
      "KPIs replace the need for a business case"
    ],
    "correct_answer": "A"
  },
  {
    "id": "LO4-q4",
    "lo_number": 4,
    "lo_code": "LO4",
    "lo_title": "Business Case",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — The document that justifies the project: why we're doing it, what we get, what it costs, what the risks are.. __(b)__ — External-environment scan: Political, Economic, Sociological, Technological, Legal, Environmental..",
    "marks": 2,
    "explanation": "Business case matches \"The document that justifies the project: why we're doing it, what we get, what it costs, what the risks are.\", and PESTLE matches \"External-environment scan: Political, Economic, Sociological, Technological, Legal, Environmental.\".",
    "dropdowns": {
      "a": [
        "Business case",
        "PESTLE",
        "SWOT",
        "VUCA"
      ],
      "b": [
        "PESTLE",
        "Business case",
        "SWOT",
        "VUCA"
      ]
    },
    "correct_answers": {
      "a": "Business case",
      "b": "PESTLE"
    }
  },
  {
    "id": "LO4-q8",
    "lo_number": 4,
    "lo_code": "LO4",
    "lo_title": "Business Case",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — Internal-and-external scan: Strengths, Weaknesses, Opportunities, Threats.. __(b)__ — Four conditions to plan against: Volatility, Uncertainty, Complexity, Ambiguity..",
    "marks": 2,
    "explanation": "SWOT matches \"Internal-and-external scan: Strengths, Weaknesses, Opportunities, Threats.\", and VUCA matches \"Four conditions to plan against: Volatility, Uncertainty, Complexity, Ambiguity.\".",
    "dropdowns": {
      "a": [
        "SWOT",
        "Business case",
        "PESTLE",
        "VUCA"
      ],
      "b": [
        "VUCA",
        "Business case",
        "PESTLE",
        "SWOT"
      ]
    },
    "correct_answers": {
      "a": "SWOT",
      "b": "VUCA"
    }
  },
  {
    "id": "LO4-q68",
    "lo_number": 4,
    "lo_code": "LO4",
    "lo_title": "Business Case",
    "type": "mcq",
    "prompt": "What project document specifically enables a project manager to agree on success criteria with the project sponsor and other stakeholders?",
    "marks": 1,
    "explanation": "Correct answer: The business case.",
    "options": [
      "The SWOT analysis chart",
      "The business case",
      "The risk log",
      "The daily status update"
    ],
    "correct_answer": "B"
  },
  {
    "id": "LO5-q5",
    "lo_number": 5,
    "lo_code": "LO5",
    "lo_title": "Procurement",
    "type": "dropdown",
    "prompt": "Match the reimbursement method to the scope situation. When scope is __(a)__, fixed price is most appropriate. When scope is still evolving, __(b)__ is most appropriate.",
    "marks": 2,
    "explanation": "Fixed price needs defined scope. Per unit quantity (time and materials) allows the buyer to pay for what's used as scope clarifies.",
    "dropdowns": {
      "a": [
        "clearly defined",
        "vague and evolving",
        "high risk",
        "unconstrained"
      ],
      "b": [
        "per unit quantity",
        "fixed price",
        "lump sum",
        "phased fixed price"
      ]
    },
    "correct_answers": {
      "a": "clearly defined",
      "b": "per unit quantity"
    }
  },
  {
    "id": "LO5-q6",
    "lo_number": 5,
    "lo_code": "LO5",
    "lo_title": "Procurement",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — A document setting out how the project will acquire goods and services.. __(b)__ — Whether the project produces something in-house or buys it from a supplier..",
    "marks": 2,
    "explanation": "Procurement strategy matches \"A document setting out how the project will acquire goods and services.\", and Make-or-buy decision matches \"Whether the project produces something in-house or buys it from a supplier.\".",
    "dropdowns": {
      "a": [
        "Procurement strategy",
        "Make-or-buy decision",
        "Invitation to Tender (ITT)",
        "BATNA"
      ],
      "b": [
        "Make-or-buy decision",
        "Procurement strategy",
        "Invitation to Tender (ITT)",
        "BATNA"
      ]
    },
    "correct_answers": {
      "a": "Procurement strategy",
      "b": "Make-or-buy decision"
    }
  },
  {
    "id": "LO5-q10",
    "lo_number": 5,
    "lo_code": "LO5",
    "lo_title": "Procurement",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — A formal request to suppliers to bid for the work, with instructions, requirements and evaluation criteria.. __(b)__ — Best Alternative to a Negotiated Agreement. What you fall back to if negotiation fails..",
    "marks": 2,
    "explanation": "Invitation to Tender (ITT) matches \"A formal request to suppliers to bid for the work, with instructions, requirements and evaluation criteria.\", and BATNA matches \"Best Alternative to a Negotiated Agreement. What you fall back to if negotiation fails.\".",
    "dropdowns": {
      "a": [
        "Invitation to Tender (ITT)",
        "Procurement strategy",
        "Make-or-buy decision",
        "BATNA"
      ],
      "b": [
        "BATNA",
        "Procurement strategy",
        "Make-or-buy decision",
        "Invitation to Tender (ITT)"
      ]
    },
    "correct_answers": {
      "a": "Invitation to Tender (ITT)",
      "b": "BATNA"
    }
  },
  {
    "id": "LO5-q30",
    "lo_number": 5,
    "lo_code": "LO5",
    "lo_title": "Procurement",
    "type": "dropdown",
    "prompt": "A colleague claims cost plus fee always favours the supplier. Correcting this: it can be __(a)__ (more profit if costs rise) or __(b)__ (less protection if costs rise, higher supplier risk).",
    "marks": 2,
    "explanation": "Cost plus fee can be percentage-based (supplier profit rises with cost) or fixed-fee (supplier profit is capped, so rising costs increase their risk) — it doesn't automatically favour the supplier.",
    "dropdowns": {
      "a": [
        "percentage-based",
        "always fixed price",
        "always target cost",
        "always per unit"
      ],
      "b": [
        "fixed-fee",
        "percentage-based",
        "unlimited",
        "government-mandated"
      ]
    },
    "correct_answers": {
      "a": "percentage-based",
      "b": "fixed-fee"
    }
  },
  {
    "id": "LO6-q4",
    "lo_number": 6,
    "lo_code": "LO6",
    "lo_title": "Reviews",
    "type": "dropdown",
    "prompt": "The PM can prepare a report on __(a)__ to track project spend against the value of work achieved so far. The three key factors that should always be considered in reviews are __(b)__.",
    "marks": 2,
    "explanation": "Earned value tracks spend vs value of work achieved. Quality, time and cost are the three classic constraints reviews always cover.",
    "dropdowns": {
      "a": [
        "earned value",
        "budget",
        "benefits",
        "project deliverables"
      ],
      "b": [
        "quality, time and cost",
        "risks, issues and change",
        "benefits, budget and quality",
        "risks, time and cost"
      ]
    },
    "correct_answers": {
      "a": "earned value",
      "b": "quality, time and cost"
    }
  },
  {
    "id": "LO6-q25",
    "lo_number": 6,
    "lo_code": "LO6",
    "lo_title": "Reviews",
    "type": "dropdown",
    "prompt": "A colleague says re-planning is a sign of failure. Correcting this: re-planning is the project responding to __(a)__, and is not triggered by __(b)__ or lessons-learned application alone.",
    "marks": 2,
    "explanation": "Re-planning responds to new information (risk, scope, performance); governance structure and lessons-learned application by themselves don't trigger it.",
    "dropdowns": {
      "a": [
        "new information",
        "bad luck",
        "poor staff",
        "weather"
      ],
      "b": [
        "governance structure",
        "risk registers",
        "audits",
        "decision gates"
      ]
    },
    "correct_answers": {
      "a": "new information",
      "b": "governance structure"
    }
  },
  {
    "id": "LO7-q5",
    "lo_number": 7,
    "lo_code": "LO7",
    "lo_title": "Assurance",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — An independent check that gives the sponsor and governance board confidence the project is actually on track, not just being reported as on track.. __(b)__ — A schedule of who will check what, when, and how findings get reported. Must be proportionate, risk-targeted and independent..",
    "marks": 2,
    "explanation": "Assurance matches \"An independent check that gives the sponsor and governance board confidence the project is actually on track, not just being reported as on track.\", and Assurance plan matches \"A schedule of who will check what, when, and how findings get reported. Must be proportionate, risk-targeted and independent.\".",
    "dropdowns": {
      "a": [
        "Assurance",
        "Assurance plan",
        "Controls",
        "Compliance"
      ],
      "b": [
        "Assurance plan",
        "Assurance",
        "Controls",
        "Compliance"
      ]
    },
    "correct_answers": {
      "a": "Assurance",
      "b": "Assurance plan"
    }
  },
  {
    "id": "LO7-q9",
    "lo_number": 7,
    "lo_code": "LO7",
    "lo_title": "Assurance",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — The management system (policies, procedures, standards) the project uses day to day to keep risks contained.. __(b)__ — Routine checks (audits, PMO reviews, QA) that confirm the controls are being used as intended..",
    "marks": 2,
    "explanation": "Controls matches \"The management system (policies, procedures, standards) the project uses day to day to keep risks contained.\", and Compliance matches \"Routine checks (audits, PMO reviews, QA) that confirm the controls are being used as intended.\".",
    "dropdowns": {
      "a": [
        "Controls",
        "Assurance",
        "Assurance plan",
        "Compliance"
      ],
      "b": [
        "Compliance",
        "Assurance",
        "Assurance plan",
        "Controls"
      ]
    },
    "correct_answers": {
      "a": "Controls",
      "b": "Compliance"
    }
  },
  {
    "id": "LO7-q19",
    "lo_number": 7,
    "lo_code": "LO7",
    "lo_title": "Assurance",
    "type": "mcq",
    "prompt": "A colleague claims assurance happens only at the end of a project to confirm it was done correctly. What's correct?",
    "marks": 1,
    "explanation": "Assurance runs throughout the life cycle, timed to inform decisions — not a single end-of-project check.",
    "options": [
      "Assurance is carried out at multiple points through the life cycle, ideally aligned to decision gates so findings can inform decisions in time",
      "Assurance is a single, one-off activity at project closure",
      "Assurance only occurs if the sponsor requests it retrospectively",
      "Assurance replaces the need for decision gates entirely"
    ],
    "correct_answer": "A"
  },
  {
    "id": "LO7-q27",
    "lo_number": 7,
    "lo_code": "LO7",
    "lo_title": "Assurance",
    "type": "scenario_mcq",
    "prompt": "Which named external body is given as an example of an external audit function?",
    "marks": 1,
    "explanation": "The NAO is the named example of an external audit body providing independent review.",
    "options": [
      "The NAO (National Audit Office)",
      "The Steering Board",
      "The Product Owner",
      "The PMO"
    ],
    "correct_answer": "A"
  },
  {
    "id": "LO8-q5",
    "lo_number": 8,
    "lo_code": "LO8",
    "lo_title": "Transition Management",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — The handover of project outputs to business-as-usual, including all the work to make the change stick.. __(b)__ — How prepared BAU is to receive, use and benefit from the project's outputs..",
    "marks": 2,
    "explanation": "Transition matches \"The handover of project outputs to business-as-usual, including all the work to make the change stick.\", and Business readiness matches \"How prepared BAU is to receive, use and benefit from the project's outputs.\".",
    "dropdowns": {
      "a": [
        "Transition",
        "Business readiness",
        "Change impact analysis",
        "Knowledge transfer"
      ],
      "b": [
        "Business readiness",
        "Transition",
        "Change impact analysis",
        "Knowledge transfer"
      ]
    },
    "correct_answers": {
      "a": "Transition",
      "b": "Business readiness"
    }
  },
  {
    "id": "LO8-q9",
    "lo_number": 8,
    "lo_code": "LO8",
    "lo_title": "Transition Management",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — A structured assessment of how the change affects people, performance, processes, systems and culture.. __(b)__ — Moving information, skills and expertise from the project team to operational users..",
    "marks": 2,
    "explanation": "Change impact analysis matches \"A structured assessment of how the change affects people, performance, processes, systems and culture.\", and Knowledge transfer matches \"Moving information, skills and expertise from the project team to operational users.\".",
    "dropdowns": {
      "a": [
        "Change impact analysis",
        "Transition",
        "Business readiness",
        "Knowledge transfer"
      ],
      "b": [
        "Knowledge transfer",
        "Transition",
        "Business readiness",
        "Change impact analysis"
      ]
    },
    "correct_answers": {
      "a": "Change impact analysis",
      "b": "Knowledge transfer"
    }
  },
  {
    "id": "LO8-q15",
    "lo_number": 8,
    "lo_code": "LO8",
    "lo_title": "Transition Management",
    "type": "dropdown",
    "prompt": "For a building project, transition handover content includes user manuals, operating procedures, __(a)__, and commissioning certificates. For a linear project generally, it also includes process maps and ownership of __(b)__ relationships.",
    "marks": 2,
    "explanation": "Building-project handover includes user manuals, procedures, asset registers, drawings, survey data, H&S files and commissioning certificates; linear handovers generally include process maps and supplier relationship ownership.",
    "dropdowns": {
      "a": [
        "asset registers",
        "risk appetite statements",
        "benefit realisation plans only",
        "team org charts"
      ],
      "b": [
        "supplier",
        "sponsor",
        "regulator",
        "auditor"
      ]
    },
    "correct_answers": {
      "a": "asset registers",
      "b": "supplier"
    }
  },
  {
    "id": "LO8-q25",
    "lo_number": 8,
    "lo_code": "LO8",
    "lo_title": "Transition Management",
    "type": "dropdown",
    "prompt": "A colleague claims knowledge transfer is a single handover event. Correcting this: it is __(a)__, moving through Launch, Experimentation, Practising and __(b)__.",
    "marks": 2,
    "explanation": "Knowledge transfer is progressive across four stages ending in Embedded, not a single event.",
    "dropdowns": {
      "a": [
        "progressive",
        "one-off",
        "optional",
        "sponsor-only"
      ],
      "b": [
        "Embedded",
        "Closure",
        "Concept",
        "Deployment"
      ]
    },
    "correct_answers": {
      "a": "progressive",
      "b": "Embedded"
    }
  },
  {
    "id": "LO9-q6",
    "lo_number": 9,
    "lo_code": "LO9",
    "lo_title": "Benefits Management",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — A measurable, positive change the organisation gets from using the project's outputs. Money saved, jobs created, satisfaction up, time down.. __(b)__ — A measurable downside that comes with the change. Real, not just a risk: redundancies, lost familiarity, transition disruption..",
    "marks": 2,
    "explanation": "Benefit matches \"A measurable, positive change the organisation gets from using the project's outputs. Money saved, jobs created, satisfaction up, time down.\", and Disbenefit matches \"A measurable downside that comes with the change. Real, not just a risk: redundancies, lost familiarity, transition disruption.\".",
    "dropdowns": {
      "a": [
        "Benefit",
        "Disbenefit",
        "Output",
        "Outcome"
      ],
      "b": [
        "Disbenefit",
        "Benefit",
        "Output",
        "Outcome"
      ]
    },
    "correct_answers": {
      "a": "Benefit",
      "b": "Disbenefit"
    }
  },
  {
    "id": "LO9-q10",
    "lo_number": 9,
    "lo_code": "LO9",
    "lo_title": "Benefits Management",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — The thing the project hands over: the new system, the renovated building, the trained team.. __(b)__ — The change in behaviour or capability that the output enables. Bridges output and benefit..",
    "marks": 2,
    "explanation": "Output matches \"The thing the project hands over: the new system, the renovated building, the trained team.\", and Outcome matches \"The change in behaviour or capability that the output enables. Bridges output and benefit.\".",
    "dropdowns": {
      "a": [
        "Output",
        "Benefit",
        "Disbenefit",
        "Outcome"
      ],
      "b": [
        "Outcome",
        "Benefit",
        "Disbenefit",
        "Output"
      ]
    },
    "correct_answers": {
      "a": "Output",
      "b": "Outcome"
    }
  },
  {
    "id": "LO9-q19",
    "lo_number": 9,
    "lo_code": "LO9",
    "lo_title": "Benefits Management",
    "type": "mcq",
    "prompt": "A colleague claims intangible benefits can't be included because they can't be measured. What's correct?",
    "marks": 1,
    "explanation": "Intangible benefits (reputation, morale) should still be defined with proxy metrics rather than excluded.",
    "options": [
      "Intangible benefits should be included, using proxy measures like engagement scores or NPS — unmeasured isn't the same as unmeasurable",
      "Intangible benefits are excluded from all APM guidance",
      "Only financial benefits count as real benefits",
      "Intangible benefits are the project manager's sole responsibility to invent"
    ],
    "correct_answer": "A"
  },
  {
    "id": "LO10-q37",
    "lo_number": 10,
    "lo_code": "LO10",
    "lo_title": "Stakeholder Engagement and Communications Management",
    "type": "mcq",
    "prompt": "What is the recommended strategy for a stakeholder with high power, high interest, and a positive attitude?",
    "marks": 1,
    "explanation": "Correct answer: Regular engagement to maintain their support and commitment to champion the project.",
    "options": [
      "Give them little engagement",
      "Regular engagement to maintain their support and commitment to champion the project",
      "Provide them with glossaries to improve technical skills",
      "Isolate them from other stakeholders"
    ],
    "correct_answer": "B"
  },
  {
    "id": "LO10-q39",
    "lo_number": 10,
    "lo_code": "LO10",
    "lo_title": "Stakeholder Engagement and Communications Management",
    "type": "mcq",
    "prompt": "Which of the following is a classic example of a stakeholder with high power, low interest, and a neutral attitude?",
    "marks": 1,
    "explanation": "Correct answer: A regulatory body such as the Health and Safety Executive.",
    "options": [
      "The primary project sponsor",
      "A regulatory body such as the Health and Safety Executive",
      "A community member living miles away from the project",
      "A heavily invested business owner"
    ],
    "correct_answer": "B"
  },
  {
    "id": "LO10-q40",
    "lo_number": 10,
    "lo_code": "LO10",
    "lo_title": "Stakeholder Engagement and Communications Management",
    "type": "mcq",
    "prompt": "How should a project manager engage with a low power, low interest stakeholder who has a neutral attitude?",
    "marks": 1,
    "explanation": "Correct answer: Provide little engagement, such as just a newsletter or similar.",
    "options": [
      "Provide intensive daily face-to-face meetings",
      "Exclude them from all communications",
      "Provide little engagement, such as just a newsletter or similar",
      "Assign them a senior management sponsor"
    ],
    "correct_answer": "C"
  },
  {
    "id": "LO10-q44",
    "lo_number": 10,
    "lo_code": "LO10",
    "lo_title": "Stakeholder Engagement and Communications Management",
    "type": "mcq",
    "prompt": "Which of the following is a key element that should be addressed in a stakeholder communication plan?",
    "marks": 1,
    "explanation": "Correct answer: The level of feedback that should be solicited or expected.",
    "options": [
      "The specific technical coding standards",
      "The level of feedback that should be solicited or expected",
      "The individual salaries of the project team",
      "The procurement strategy for office supplies"
    ],
    "correct_answer": "B"
  },
  {
    "id": "LO11-q6",
    "lo_number": 11,
    "lo_code": "LO11",
    "lo_title": "Conflict Resolution",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — When two or more parties have differing opinions or attitudes towards something or someone, and the difference is not easily reconciled.. __(b)__ — A model that maps five conflict responses against two axes: how much you push for your own needs vs how much you accommodate others..",
    "marks": 2,
    "explanation": "Conflict matches \"When two or more parties have differing opinions or attitudes towards something or someone, and the difference is not easily reconciled.\", and Thomas Kilmann Conflict Mode Instrument (TKI) matches \"A model that maps five conflict responses against two axes: how much you push for your own needs vs how much you accommodate others.\".",
    "dropdowns": {
      "a": [
        "Conflict",
        "Thomas Kilmann Conflict Mode Instrument (TKI)",
        "Compete",
        "Avoid"
      ],
      "b": [
        "Thomas Kilmann Conflict Mode Instrument (TKI)",
        "Conflict",
        "Compete",
        "Avoid"
      ]
    },
    "correct_answers": {
      "a": "Conflict",
      "b": "Thomas Kilmann Conflict Mode Instrument (TKI)"
    }
  },
  {
    "id": "LO11-q10",
    "lo_number": 11,
    "lo_code": "LO11",
    "lo_title": "Conflict Resolution",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — I win, you lose. High assertiveness, low cooperation. Use for urgent decisions or non-negotiables.. __(b)__ — I lose, you lose. Low both ways. Use when the issue is too small to be worth the disruption..",
    "marks": 2,
    "explanation": "Compete matches \"I win, you lose. High assertiveness, low cooperation. Use for urgent decisions or non-negotiables.\", and Avoid matches \"I lose, you lose. Low both ways. Use when the issue is too small to be worth the disruption.\".",
    "dropdowns": {
      "a": [
        "Compete",
        "Conflict",
        "Thomas Kilmann Conflict Mode Instrument (TKI)",
        "Avoid"
      ],
      "b": [
        "Avoid",
        "Conflict",
        "Thomas Kilmann Conflict Mode Instrument (TKI)",
        "Compete"
      ]
    },
    "correct_answers": {
      "a": "Compete",
      "b": "Avoid"
    }
  },
  {
    "id": "LO11-q66",
    "lo_number": 11,
    "lo_code": "LO11",
    "lo_title": "Conflict Resolution",
    "type": "mcq",
    "prompt": "Why should a project manager use a neutral tone, language, and body language during conflict resolution?",
    "marks": 1,
    "explanation": "Correct answer: To ensure less defensiveness and encourage more communication.",
    "options": [
      "To demonstrate dominance over the project team",
      "To ensure less defensiveness and encourage more communication",
      "To show they do not care about the outcome",
      "To speed up the adoption phase of the project"
    ],
    "correct_answer": "B"
  },
  {
    "id": "LO11-q78",
    "lo_number": 11,
    "lo_code": "LO11",
    "lo_title": "Conflict Resolution",
    "type": "mcq",
    "prompt": "To gain commitment by incorporating others' concerns into a consensual decision, a project manager should use:",
    "marks": 1,
    "explanation": "Correct answer: Collaborating.",
    "options": [
      "Accommodating",
      "Compromising",
      "Collaborating",
      "Avoiding"
    ],
    "correct_answer": "C"
  },
  {
    "id": "LO12-q4",
    "lo_number": 12,
    "lo_code": "LO12",
    "lo_title": "Leadership",
    "type": "scenario_mcq",
    "prompt": "Which combination of factors does Herzberg's theory identify as hygiene factors rather than motivators?",
    "marks": 1,
    "explanation": "Hygiene factors prevent dissatisfaction (pay, conditions, policies). Motivators create satisfaction (recognition, achievement, responsibility, growth).",
    "options": [
      "Recognition and achievement.",
      "Pay and working conditions.",
      "Responsibility and growth.",
      "Purpose and meaning."
    ],
    "correct_answer": "B"
  },
  {
    "id": "LO12-q17",
    "lo_number": 12,
    "lo_code": "LO12",
    "lo_title": "Leadership",
    "type": "scenario_mcq",
    "prompt": "Which quadrant of emotional intelligence is being used when a leader manages relationships and shows awareness of how others are feeling?",
    "marks": 1,
    "explanation": "Interpersonal EQ covers regard for others, awareness of others and relationship management.",
    "options": [
      "Interpersonal.",
      "Intrapersonal.",
      "Autocratic.",
      "Hygiene-based."
    ],
    "correct_answer": "A"
  },
  {
    "id": "LO12-q77",
    "lo_number": 12,
    "lo_code": "LO12",
    "lo_title": "Leadership",
    "type": "mcq",
    "prompt": "If a project manager notices a sudden, critical issue threatening the immediate survival of the project, which style is best to temporarily adopt?",
    "marks": 1,
    "explanation": "Correct answer: Autocratic / Directive.",
    "options": [
      "Laissez-faire",
      "Delegative",
      "Autocratic / Directive",
      "Coaching"
    ],
    "correct_answer": "C"
  },
  {
    "id": "LO13-q4",
    "lo_number": 13,
    "lo_code": "LO13",
    "lo_title": "Team Management",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — Guiding a group of people to work effectively towards a common goal.. __(b)__ — Identifies nine team roles. Effective teams have a mix..",
    "marks": 2,
    "explanation": "Team management matches \"Guiding a group of people to work effectively towards a common goal.\", and Belbin matches \"Identifies nine team roles. Effective teams have a mix.\".",
    "dropdowns": {
      "a": [
        "Team management",
        "Belbin",
        "Margerison McCann",
        "Myers-Briggs Type Indicator (MBTI)"
      ],
      "b": [
        "Belbin",
        "Team management",
        "Margerison McCann",
        "Myers-Briggs Type Indicator (MBTI)"
      ]
    },
    "correct_answers": {
      "a": "Team management",
      "b": "Belbin"
    }
  },
  {
    "id": "LO14-q5",
    "lo_number": 14,
    "lo_code": "LO14",
    "lo_title": "Diversity and Inclusion",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — The mix of differences in a team: background, experience, identity, perspective.. __(b)__ — Making sure those differences are valued and people can contribute as themselves..",
    "marks": 2,
    "explanation": "Diversity matches \"The mix of differences in a team: background, experience, identity, perspective.\", and Inclusion matches \"Making sure those differences are valued and people can contribute as themselves.\".",
    "dropdowns": {
      "a": [
        "Diversity",
        "Inclusion",
        "Protected characteristic",
        "Conscious bias"
      ],
      "b": [
        "Inclusion",
        "Diversity",
        "Protected characteristic",
        "Conscious bias"
      ]
    },
    "correct_answers": {
      "a": "Diversity",
      "b": "Inclusion"
    }
  },
  {
    "id": "LO15-q33",
    "lo_number": 15,
    "lo_code": "LO15",
    "lo_title": "Ethics, Compliance and Professionalism",
    "type": "mcq",
    "prompt": "You are sponsoring a project to build a pedestrian bridge. A new regulation has been issued which states that large infrastructure projects must now meet a certain standard of sustainability. Which response would be most appropriate in light of the new regulation?",
    "marks": 1,
    "explanation": "Correct answer: Add to your risk register, to include any impact the regulation might have on your project.",
    "options": [
      "Revisit the project business case to review the project schedule",
      "Add to your risk register, to include any impact the regulation might have on your project",
      "Try to get the project through its next stage gate quicker, so you won’t be affected by the new regulation",
      "All of the above"
    ],
    "correct_answer": "B"
  },
  {
    "id": "LO16-q3",
    "lo_number": 16,
    "lo_code": "LO16",
    "lo_title": "Requirements Management",
    "type": "dropdown",
    "prompt": "During analysis, you decide to perform a Function Cost Analysis to identify the __(a)__ of the requirements to the organisation. You then use the __(b)__ technique to prioritise the requirements.",
    "marks": 2,
    "explanation": "Function Cost Analysis identifies value contribution. MoSCoW (Must, Should, Could, Won't) is the named prioritisation technique.",
    "dropdowns": {
      "a": [
        "cost",
        "value",
        "investment",
        "risk"
      ],
      "b": [
        "SMART",
        "SWOT",
        "PESTLE",
        "MoSCoW"
      ]
    },
    "correct_answers": {
      "a": "value",
      "b": "MoSCoW"
    }
  },
  {
    "id": "LO16-q4",
    "lo_number": 16,
    "lo_code": "LO16",
    "lo_title": "Requirements Management",
    "type": "scenario_mcq",
    "prompt": "In which configuration management step would you check that completed deliverables match the documented configuration?",
    "marks": 1,
    "explanation": "Verification audit confirms deliverables conform to requirements and to documented configuration. Status accounting tracks; identification labels; planning sets process.",
    "options": [
      "Planning",
      "Identification",
      "Status accounting",
      "Verification audit"
    ],
    "correct_answer": "D"
  },
  {
    "id": "LO17-q1",
    "lo_number": 17,
    "lo_code": "LO17",
    "lo_title": "Solutions Development",
    "type": "scenario_mcq",
    "prompt": "You are starting a new role as PM. How will you evaluate and prioritise your project's objectives and requirements to deliver the optimal solution?",
    "marks": 1,
    "explanation": "SMART checks the quality of each requirement; MoSCoW prioritises them. Quick wins, history-only and equal weighting all fail to anchor priority in value.",
    "options": [
      "Prioritise by ease of implementation for quick wins.",
      "Prioritise based on historical data from similar projects.",
      "Check requirements are SMART and prioritise with MoSCoW (Must, Should, Could, Won't).",
      "Treat all objectives as equally important for balance."
    ],
    "correct_answer": "C"
  },
  {
    "id": "LO17-q4",
    "lo_number": 17,
    "lo_code": "LO17",
    "lo_title": "Solutions Development",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — Choosing the best way to satisfy the agreed requirements.. __(b)__ — Prioritisation technique: Must, Should, Could, Won't have..",
    "marks": 2,
    "explanation": "Solutions development matches \"Choosing the best way to satisfy the agreed requirements.\", and MoSCoW matches \"Prioritisation technique: Must, Should, Could, Won't have.\".",
    "dropdowns": {
      "a": [
        "Solutions development",
        "MoSCoW",
        "Function (Cost) Analysis",
        "Minimum Viable Product (MVP)"
      ],
      "b": [
        "MoSCoW",
        "Solutions development",
        "Function (Cost) Analysis",
        "Minimum Viable Product (MVP)"
      ]
    },
    "correct_answers": {
      "a": "Solutions development",
      "b": "MoSCoW"
    }
  },
  {
    "id": "LO18-q4",
    "lo_number": 18,
    "lo_code": "LO18",
    "lo_title": "Quality Management",
    "type": "dropdown",
    "prompt": "Quality Control verifies that the project's __(a)__ meet acceptance criteria, whereas Quality Assurance provides confidence that the right __(b)__ have been followed.",
    "marks": 2,
    "explanation": "QC = outputs vs acceptance criteria. QA = processes and methods. The reward phrase pair.",
    "dropdowns": {
      "a": [
        "outputs",
        "stakeholders",
        "schedules",
        "risks"
      ],
      "b": [
        "processes and methods",
        "approvals",
        "contracts",
        "tests"
      ]
    },
    "correct_answers": {
      "a": "outputs",
      "b": "processes and methods"
    }
  },
  {
    "id": "LO18-q5",
    "lo_number": 18,
    "lo_code": "LO18",
    "lo_title": "Quality Management",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — The discipline that ensures outputs meet requirements through planning, control and assurance.. __(b)__ — The document setting out how quality will be planned, controlled and assured..",
    "marks": 2,
    "explanation": "Quality management matches \"The discipline that ensures outputs meet requirements through planning, control and assurance.\", and Quality plan matches \"The document setting out how quality will be planned, controlled and assured.\".",
    "dropdowns": {
      "a": [
        "Quality management",
        "Quality plan",
        "Quality indicator",
        "Acceptance criteria"
      ],
      "b": [
        "Quality plan",
        "Quality management",
        "Quality indicator",
        "Acceptance criteria"
      ]
    },
    "correct_answers": {
      "a": "Quality management",
      "b": "Quality plan"
    }
  },
  {
    "id": "LO18-q9",
    "lo_number": 18,
    "lo_code": "LO18",
    "lo_title": "Quality Management",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — A measurable parameter used to assess performance against quality standards.. __(b)__ — Specific pass/fail conditions that confirm a deliverable meets requirements..",
    "marks": 2,
    "explanation": "Quality indicator matches \"A measurable parameter used to assess performance against quality standards.\", and Acceptance criteria matches \"Specific pass/fail conditions that confirm a deliverable meets requirements.\".",
    "dropdowns": {
      "a": [
        "Quality indicator",
        "Quality management",
        "Quality plan",
        "Acceptance criteria"
      ],
      "b": [
        "Acceptance criteria",
        "Quality management",
        "Quality plan",
        "Quality indicator"
      ]
    },
    "correct_answers": {
      "a": "Quality indicator",
      "b": "Acceptance criteria"
    }
  },
  {
    "id": "LO19-q3",
    "lo_number": 19,
    "lo_code": "LO19",
    "lo_title": "Integrated Planning",
    "type": "dropdown",
    "prompt": "The exact contents of a PMP may vary between projects due to size, complexity and __(a)__. Typical contents include benefits, scope, timeline, project team organisation, budget and __(b)__.",
    "marks": 2,
    "explanation": "Life cycle choice shapes content and update cadence. Management strategies (risk, quality, comms etc.) are the wide-ranging section covered last in the typical list.",
    "dropdowns": {
      "a": [
        "choice of life cycle",
        "project sponsor's preference",
        "project duration",
        "choice of solution"
      ],
      "b": [
        "management strategies",
        "detailed work plans",
        "design specifications",
        "relevant legal contracts"
      ]
    },
    "correct_answers": {
      "a": "choice of life cycle",
      "b": "management strategies"
    }
  },
  {
    "id": "LO19-q5",
    "lo_number": 19,
    "lo_code": "LO19",
    "lo_title": "Integrated Planning",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — Bringing all the project's plans and processes together into one consistent document.. __(b)__ — The single self-contained document setting out how the project will be managed: why, what, when, who, how much, where, how..",
    "marks": 2,
    "explanation": "Integrated planning matches \"Bringing all the project's plans and processes together into one consistent document.\", and Project Management Plan (PMP) matches \"The single self-contained document setting out how the project will be managed: why, what, when, who, how much, where, how.\".",
    "dropdowns": {
      "a": [
        "Integrated planning",
        "Project Management Plan (PMP)",
        "Product Breakdown Structure (PBS)",
        "Work Breakdown Structure (WBS)"
      ],
      "b": [
        "Project Management Plan (PMP)",
        "Integrated planning",
        "Product Breakdown Structure (PBS)",
        "Work Breakdown Structure (WBS)"
      ]
    },
    "correct_answers": {
      "a": "Integrated planning",
      "b": "Project Management Plan (PMP)"
    }
  },
  {
    "id": "LO19-q9",
    "lo_number": 19,
    "lo_code": "LO19",
    "lo_title": "Integrated Planning",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — Hierarchical breakdown of the project's products or deliverables.. __(b)__ — Hierarchical breakdown of the work needed to produce the deliverables..",
    "marks": 2,
    "explanation": "Product Breakdown Structure (PBS) matches \"Hierarchical breakdown of the project's products or deliverables.\", and Work Breakdown Structure (WBS) matches \"Hierarchical breakdown of the work needed to produce the deliverables.\".",
    "dropdowns": {
      "a": [
        "Product Breakdown Structure (PBS)",
        "Integrated planning",
        "Project Management Plan (PMP)",
        "Work Breakdown Structure (WBS)"
      ],
      "b": [
        "Work Breakdown Structure (WBS)",
        "Integrated planning",
        "Project Management Plan (PMP)",
        "Product Breakdown Structure (PBS)"
      ]
    },
    "correct_answers": {
      "a": "Product Breakdown Structure (PBS)",
      "b": "Work Breakdown Structure (WBS)"
    }
  },
  {
    "id": "LO20-q4",
    "lo_number": 20,
    "lo_code": "LO20",
    "lo_title": "Schedule Management",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — The time-based plan of when activities will be done and by whom.. __(b)__ — What the project delivers (the thing)..",
    "marks": 2,
    "explanation": "Schedule matches \"The time-based plan of when activities will be done and by whom.\", and Output matches \"What the project delivers (the thing).\".",
    "dropdowns": {
      "a": [
        "Schedule",
        "Output",
        "Outcome",
        "Benefit"
      ],
      "b": [
        "Output",
        "Schedule",
        "Outcome",
        "Benefit"
      ]
    },
    "correct_answers": {
      "a": "Schedule",
      "b": "Output"
    }
  },
  {
    "id": "LO20-q8",
    "lo_number": 20,
    "lo_code": "LO20",
    "lo_title": "Schedule Management",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — The change in behaviour or capability enabled by the output.. __(b)__ — The measurable improvement that flows from the outcome..",
    "marks": 2,
    "explanation": "Outcome matches \"The change in behaviour or capability enabled by the output.\", and Benefit matches \"The measurable improvement that flows from the outcome.\".",
    "dropdowns": {
      "a": [
        "Outcome",
        "Schedule",
        "Output",
        "Benefit"
      ],
      "b": [
        "Benefit",
        "Schedule",
        "Output",
        "Outcome"
      ]
    },
    "correct_answers": {
      "a": "Outcome",
      "b": "Benefit"
    }
  },
  {
    "id": "LO20-q75",
    "lo_number": 20,
    "lo_code": "LO20",
    "lo_title": "Schedule Management",
    "type": "mcq",
    "prompt": "How can a project manager proactively manage a critical path schedule if a critical task is falling behind?",
    "marks": 1,
    "explanation": "Correct answer: By moving resource from non-critical to critical activities, utilising the available float.",
    "options": [
      "By changing the project scope without approval",
      "By moving resource from non-critical to critical activities, utilising the available float",
      "By ignoring the delay and hoping to catch up later",
      "By extending the critical chain buffer"
    ],
    "correct_answer": "B"
  },
  {
    "id": "LO21-q2",
    "lo_number": 21,
    "lo_code": "LO21",
    "lo_title": "Resource Management",
    "type": "mcq",
    "prompt": "You are running a workshop to produce a RACI matrix with your project team. Which statement best supports this task?",
    "marks": 1,
    "explanation": "The OBS (who) combined with the WBS (what) is the standard input to a RACI. Using WBS alone or having the PM dictate undermines team co-production.",
    "options": [
      "The PM informs the team at the workshop which tasks are assigned.",
      "The WBS is used on its own to clarify roles against each task.",
      "The OBS is used with the WBS to clarify roles against each task.",
      "The PM should document every project task in the RACI."
    ],
    "correct_answer": "C"
  },
  {
    "id": "LO21-q35",
    "lo_number": 21,
    "lo_code": "LO21",
    "lo_title": "Resource Management",
    "type": "mcq",
    "prompt": "Who does a project manager typically work with to secure resources at the required times for the schedule?",
    "marks": 1,
    "explanation": "Correct answer: Resource or BAU managers.",
    "options": [
      "Only external suppliers",
      "The project sponsor solely",
      "Resource or BAU managers",
      "The assurance team"
    ],
    "correct_answer": "C"
  },
  {
    "id": "LO21-q43",
    "lo_number": 21,
    "lo_code": "LO21",
    "lo_title": "Resource Management",
    "type": "mcq",
    "prompt": "What is created when a project manager decides if team members are responsible, accountable, consulted, or informed for each task?",
    "marks": 1,
    "explanation": "Correct answer: A responsibility assignment matrix (RAM).",
    "options": [
      "A project schedule",
      "A cost breakdown structure",
      "A responsibility assignment matrix (RAM)",
      "A resource smoothing chart"
    ],
    "correct_answer": "C"
  },
  {
    "id": "LO22-q40",
    "lo_number": 22,
    "lo_code": "LO22",
    "lo_title": "Budgeting and Cost Control",
    "type": "mcq",
    "prompt": "Knowing the overall cost of a project is a good start, but what else must a project manager understand for effective project control?",
    "marks": 1,
    "explanation": "Correct answer: Where the costs fall over time in the schedule.",
    "options": [
      "Where the costs fall over time in the schedule",
      "The personal budgets of the project team members",
      "The historical costs of all previous projects in the industry",
      "The exact profit margin of all external suppliers"
    ],
    "correct_answer": "A"
  },
  {
    "id": "LO22-q59",
    "lo_number": 22,
    "lo_code": "LO22",
    "lo_title": "Budgeting and Cost Control",
    "type": "mcq",
    "prompt": "How can a project manager provide a pictorial representation of project progress using cost control techniques?",
    "marks": 1,
    "explanation": "Correct answer: By tracking the Earned Value on an Earned Value graph.",
    "options": [
      "By creating a Work Breakdown Structure",
      "By tracking the Earned Value on an Earned Value graph",
      "By drawing a project network diagram",
      "By creating a Gantt chart of indirect costs"
    ],
    "correct_answer": "B"
  },
  {
    "id": "LO23-q5",
    "lo_number": 23,
    "lo_code": "LO23",
    "lo_title": "Risk and Issue Management",
    "type": "dropdown",
    "prompt": "An identified risk has exceeded its tolerated threshold. __(a)__ provides the project team with an overview of what is expected of them when managing risk. The first step of a project team member when a risk exceeds tolerance is to inform the __(b)__.",
    "marks": 2,
    "explanation": "Clear roles and responsibilities (set in the risk management plan and RACI) tell the team how to act. A team member's first escalation is to the project manager.",
    "dropdowns": {
      "a": [
        "clear roles and responsibilities",
        "risk identification",
        "the RAID log",
        "risk appetite"
      ],
      "b": [
        "project manager",
        "project sponsor",
        "project team",
        "subject matter expert"
      ]
    },
    "correct_answers": {
      "a": "clear roles and responsibilities",
      "b": "project manager"
    }
  },
  {
    "id": "LO23-q6",
    "lo_number": 23,
    "lo_code": "LO23",
    "lo_title": "Risk and Issue Management",
    "type": "dropdown",
    "prompt": "Select the correct terms for the definitions: __(a)__ — An uncertain event that, if it happens, has a positive or negative effect on objectives.. __(b)__ — A risk that has happened, or a problem that exists now and needs resolving..",
    "marks": 2,
    "explanation": "Risk matches \"An uncertain event that, if it happens, has a positive or negative effect on objectives.\", and Issue matches \"A risk that has happened, or a problem that exists now and needs resolving.\".",
    "dropdowns": {
      "a": [
        "Risk",
        "Issue",
        "Threat",
        "Opportunity"
      ],
      "b": [
        "Issue",
        "Risk",
        "Threat",
        "Opportunity"
      ]
    },
    "correct_answers": {
      "a": "Risk",
      "b": "Issue"
    }
  },
  {
    "id": "LO23-q76",
    "lo_number": 23,
    "lo_code": "LO23",
    "lo_title": "Risk and Issue Management",
    "type": "mcq",
    "prompt": "What can a project manager request to drawdown in order to manage the mitigation of an identified risk?",
    "marks": 1,
    "explanation": "Correct answer: Planned contingency.",
    "options": [
      "The entire management reserve",
      "Planned contingency",
      "The project sponsor's salary",
      "The issue log"
    ],
    "correct_answer": "B"
  },
  {
    "id": "LO24-q5",
    "lo_number": 24,
    "lo_code": "LO24",
    "lo_title": "Change Control",
    "type": "dropdown",
    "prompt": "Complete the sentences. After a detailed evaluation, you confirm the __(a)__. You then take the change to your Project Sponsor for approval. During the approval meeting, the Sponsor will either accept, __(b)__ the change.",
    "marks": 2,
    "explanation": "Detailed evaluation confirms value vs cost. The three decision options at sponsor level are accept, reject, defer.",
    "dropdowns": {
      "a": [
        "change's value is worth the cost",
        "communication strategy is clear",
        "project's plan has already been updated",
        "configuration record has changed"
      ],
      "b": [
        "escalate or reject",
        "investigate or reject",
        "escalate or defer",
        "reject or defer"
      ]
    },
    "correct_answers": {
      "a": "change's value is worth the cost",
      "b": "reject or defer"
    }
  },
  {
    "id": "LO24-q77",
    "lo_number": 24,
    "lo_code": "LO24",
    "lo_title": "Change Control",
    "type": "mcq",
    "prompt": "According to the exam practice questions, what is the best course of action if a stakeholder suggests adding an out-of-scope feature (like a rooftop garden) when the project is on track?",
    "marks": 1,
    "explanation": "Correct answer: Log the request, assess the impact of the proposed change, and discuss with the stakeholder.",
    "options": [
      "Accept it immediately as it adds value",
      "Reject it outright to avoid any scope changes",
      "Log the request, assess the impact of the proposed change, and discuss with the stakeholder",
      "Defer it indefinitely without evaluation"
    ],
    "correct_answer": "C"
  }
];
